# Generated by Django 4.0.6 on 2022-08-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='COURSE',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
