# Generated by Django 4.0.6 on 2022-08-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_studentextra_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='ACADEMIC_YEAR',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='ID_NUMBER',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='LEVEL',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='RESIDENCE',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='TEL_NO',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='TEL_NO1',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
