# Generated by Django 3.0.5 on 2022-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20220807_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
