# Generated by Django 3.0.5 on 2022-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_slider_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
