# Generated by Django 3.0.5 on 2022-08-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20220807_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
